### ISSUE TITLE
로컬 환경과 개발 환경 분리

### ISSUE THREAD

**Issue by heenahan** [2022-2-Clone-Project-Unigram/Backend#4]

**Comment by heenahan** [comment]
## 환경 분리
```yml
# application.yml
---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local
```
application-{환경}.yml  각 환경마다 파일 생성
어떤 환경으로 실행할 것인지 vm options 추가
```
java -Dspring.profiles.active={환경}
```
